[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "aoc"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.51", features = ["derive"] }
colored = "3"
humanize-duration = "0.0.7"
thiserror = "2.0.17"
